use_frameworks!

target 'MYTableViewIndex_Example' do
  pod 'MYTableViewIndex', :path => '../'

  target 'MYTableViewIndex_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end
